// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Enum;

public partial class DealType
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public string Name { get; set; }

    public bool IsDeleted { get; set; }

    public int? MigrationId { get; set; }
}