// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class Area : BaseEntity
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public int CityId { get; set; }

    public string Name { get; set; }

    public string NameNative { get; set; }

    public string NameUnique { get; set; }

    public string Integrationkey { get; set; }



    public bool IsDeleted { get; set; }

    public int? MigrationId { get; set; }

    public virtual City City { get; set; }
}