// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class AuthenticationPlatform : BaseEntity
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public int CountryId { get; set; }

    public string Name { get; set; }

    public int AuthenticationTypeId { get; set; }

    public int DisplayOrder { get; set; }

    public string IntegrationKey { get; set; }

    public bool IsDeleted { get; set; }

    public virtual Country Country { get; set; }
}