// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class CateringConfig : BaseEntity
{
    public int? CountryId { get; set; }

    public double MinValue { get; set; }

    public double DelevaryCharge { get; set; }

    public int MinOrderHours { get; set; }

    public int MaxOrderHours { get; set; }

    public bool IsDeleted { get; set; }

    public int Id { get; set; }

    public virtual Country Country { get; set; }
}