// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class Citizenship : BaseEntity
{
    public int Id { get; set; }

    public int CountryId { get; set; }

    public int DisplayOrder { get; set; }

    public bool Status { get; set; }



    public int? MigrationId { get; set; }
}