// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class CitizenshipLang : BaseEntity
{
    public int CitizenshipId { get; set; }

    public int LangId { get; set; }

    public string Name { get; set; }



    public int? MigrationId { get; set; }
}