// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Country;

public partial class Citizenship
{
    public int Id { get; set; }

    public int CountryId { get; set; }

    public int DisplayOrder { get; set; }

    public bool Status { get; set; }

    public DateTime CreationDate { get; set; }

    public int CreationBy { get; set; }

    public DateTime? LastModificationDate { get; set; }

    public int? LastModificationBy { get; set; }

    public int? MigrationId { get; set; }
}