// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Country;

public partial class CitizenshipLang
{
    public int CitizenshipId { get; set; }

    public int LangId { get; set; }

    public string Name { get; set; }

    public DateTime CreationDate { get; set; }

    public int CreationBy { get; set; }

    public DateTime? LastModificationDate { get; set; }

    public int? Modifiedby { get; set; }

    public int? MigrationId { get; set; }
}