// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Country;

public partial class Country
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public int? DisplayOrder { get; set; }

    public string Name { get; set; }

    public string NameNative { get; set; }

    public string RegionName { get; set; }

    public string RegionNameNative { get; set; }

    public string NameUnique { get; set; }

    public string Isocode { get; set; }

    public string FlagUrl { get; set; }

    public string WebsiteUrl { get; set; }

    public string IntegrationKey { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public bool IsTwoFactorEnabled { get; set; }

    public virtual ICollection<AuthenticationPlatform> AuthenticationPlatforms { get; set; } = new List<AuthenticationPlatform>();

    public virtual ICollection<CateringConfig> CateringConfigs { get; set; } = new List<CateringConfig>();

    public virtual ICollection<City> Cities { get; set; } = new List<City>();

    public virtual Extension Extension { get; set; }

    public virtual ICollection<Language> Languages { get; set; } = new List<Language>();

    public virtual LoyaltyConfig LoyaltyConfig { get; set; }

    public virtual ICollection<OrderStatus> OrderStatuses { get; set; } = new List<OrderStatus>();

    public virtual ICollection<OrderType> OrderTypes { get; set; } = new List<OrderType>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<SocialPlatform> SocialPlatforms { get; set; } = new List<SocialPlatform>();
}