// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class Extension : BaseEntity
{
    public int CountryId { get; set; }

    public double Longitude { get; set; }

    public double Latitude { get; set; }

    public double Zoom { get; set; }

    public string PhoneRegex { get; set; }

    public string CountryPhoneCode { get; set; }

    public string OrderEmail { get; set; }

    public string CustomerServiceLine { get; set; }

    public string CurrencyIsocode { get; set; }

    public string CurrencyName { get; set; }

    public string CurrencyNameNative { get; set; }

    public bool EnableCalories { get; set; }

    public bool IsTaxInclusive { get; set; }

    public double? MinOrderValue { get; set; }

    public double? TaxPercentage { get; set; }

    public double? DeliveryChargeValue { get; set; }

    public double? TotalDiscountPercentage { get; set; }

    public double? TotalDiscountValue { get; set; }

    public double? MinOrderValueForDiscount { get; set; }

    public bool? IsMenuItemDiscountEnabled { get; set; }

    public bool? IsDealDiscountEnabled { get; set; }

    public bool? IsPromoCodeDiscountEnabled { get; set; }

    public bool? IsBogodiscountEnabled { get; set; }

    public bool? IsCountryDiscountEnabled { get; set; }

    public int? TimeDifference { get; set; }

    public int? CartExpirationTime { get; set; }

    public bool? EnableCartExpiration { get; set; }

    public bool? EnableAddressMapLocation { get; set; }

    public bool? EnableAgeConfirmation { get; set; }

    public bool? EnablePrivacyPolicyConfirmation { get; set; }

    public bool? EnableTermsConfirmation { get; set; }

    public bool? EnableMarketingConfirmation { get; set; }

    public bool? EnableOrderNotificationConfirmation { get; set; }

    public bool? EnableLoyaltyProgram { get; set; }

    public bool? EnableDeals { get; set; }

    public bool? EnableDeliveryAddress { get; set; }

    public bool? EnableDeliveryTracking { get; set; }

    public bool? EnableCmp { get; set; }

    public bool? IsCartOrderTypeRequired { get; set; }

    public bool? IsCartClearedOnOrderTypeChange { get; set; }

    public bool? IsDeliveryMappingOnClient { get; set; }

    public bool? IsGenderRequired { get; set; }

    public bool? IsBirthDateRequired { get; set; }

    public bool? IsOrderTypeOverridingCountrySettings { get; set; }

    public int? LoyaltyCurrencyCount { get; set; }

    public int? LoyaltyPointsEquivalent { get; set; }



    public bool? IsDeleted { get; set; }

    public string CmpId { get; set; }

    public int MonetaryRoundingDecimalDigits { get; set; }

    public bool IsTaxLabelShownWhenZero { get; set; }

    public string TaxLabelDisplayName { get; set; }

    public string TaxLabelDisplayNameNative { get; set; }

    public bool IsDeliveryTrackingPopupAndroidEnabled { get; set; }

    public bool IsDeliveryTrackingPopupIosenabled { get; set; }

    public string TikTokAndroidAppId { get; set; }

    public string TikTokIosAppId { get; set; }

    public bool IsLoyaltyCounterEnabled { get; set; }

    public double? LoyaltyCounterSliderSteps { get; set; }

    public int? RedemptionRatePoints { get; set; }

    public int? RedemptionRateAmount { get; set; }

    public bool? IsMinOrderCheckEnabledWithLoyaltyCounter { get; set; }

    public virtual Country Country { get; set; }
}