// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Country;

public partial class FacilityLang
{
    public int FacilityId { get; set; }

    public int LanguageId { get; set; }

    public string Name { get; set; }
}