// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class Language : BaseEntity
{
    public int Id { get; set; }

    public Guid? Guid { get; set; }

    public int CountryId { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Direction { get; set; }

    public bool IsDefault { get; set; }

    public string IntegrationKey { get; set; }



    public bool? IsDeleted { get; set; }

    public virtual Country Country { get; set; }
}