// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class LoyaltyConfig : BaseEntity
{
    public int CountryId { get; set; }

    public double RedeemPoints { get; set; }

    public double RedeemMoney { get; set; }

    public int PointsExpire { get; set; }

    public bool EnableRedeem { get; set; }



    public bool? IsDeleted { get; set; }

    public virtual Country Country { get; set; }
}