// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Country;

public partial class LoyaltyConfig
{
    public int CountryId { get; set; }

    public double RedeemPoints { get; set; }

    public double RedeemMoney { get; set; }

    public int PointsExpire { get; set; }

    public bool EnableRedeem { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual Country Country { get; set; }
}