// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Country;

public partial class OrderStatus
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public int CountryId { get; set; }

    public int DisplayOrder { get; set; }

    public string Name { get; set; }

    public string NameNative { get; set; }

    public string NameUnique { get; set; }

    public string StatusIconOn { get; set; }

    public string StatusIconOff { get; set; }

    public string IntegrationKey { get; set; }

    public bool? IsDeliveryTrackingButtonAppears { get; set; }

    public bool IsActiveOnStoreDependent { get; set; }

    public bool IsActiveOnStoreNonDependent { get; set; }

    public bool? IsNew { get; set; }

    public bool? IsCanceled { get; set; }

    public bool IsDeleted { get; set; }

    public int? MigrationId { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public virtual Country Country { get; set; }
}