// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Country;

public partial class OrderType
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public int CountryId { get; set; }

    public int TypeId { get; set; }

    public int? DisplayOrder { get; set; }

    public string Name { get; set; }

    public string NameNative { get; set; }

    public string NameUnique { get; set; }

    public string IconUrl { get; set; }

    public bool? IsStoreDependent { get; set; }

    public bool? IsTaxInclusive { get; set; }

    public bool? IsMenuItemDiscountEnabled { get; set; }

    public bool? IsDealDiscountEnabled { get; set; }

    public bool? IsPromoCodeDiscountEnabled { get; set; }

    public bool? IsBogodiscountEnabled { get; set; }

    public bool? IsCountryDiscountEnabled { get; set; }

    public double? MinOrderValue { get; set; }

    public double? TaxPercentage { get; set; }

    public double? TotalDiscountPercentage { get; set; }

    public double? TotalDiscountValue { get; set; }

    public double? MinOrderValueForDiscount { get; set; }

    public string IntegrationKey { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public int? MigrationId { get; set; }

    public bool? IsMinOrderCheckEnabledWithLoyaltyCounter { get; set; }

    public virtual Country Country { get; set; }

    public virtual ICollection<PaymentOrderType> PaymentOrderTypes { get; set; } = new List<PaymentOrderType>();

    public virtual OrderType Type { get; set; }
}