// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class PaymentRequestSource : BaseEntity
{
    public int PaymentId { get; set; }

    public string RequestSource { get; set; }

    public string DeviceModel { get; set; }

    public bool IsDeleted { get; set; }

    public int? MigrationId { get; set; }
}