// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CountryDashboard.Domain.Common;

namespace CountryDashboard.Domain.Entities.Country;

public partial class PaymentOrderType : BaseEntity
{
    public int OrderTypeId { get; set; }

    public int PaymentId { get; set; }

    public string IntegrationKey { get; set; }

    public bool IsDeleted { get; set; }

    public int? MigrationId { get; set; }

    public virtual OrderType OrderType { get; set; }
}