// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CountryDashboard.Domain.Entities.Country;

public partial class Payment
{
    public int Id { get; set; }

    public Guid Guid { get; set; }

    public int CountryId { get; set; }

    public int? StoreId { get; set; }

    public string Name { get; set; }

    public string NameNative { get; set; }

    public string NameUnique { get; set; }

    public string LogoUrl { get; set; }

    public string Url { get; set; }

    public int TypeId { get; set; }

    public string SecurityField1 { get; set; }

    public string SecurityField2 { get; set; }

    public string SecurityField3 { get; set; }

    public string SecurityField4 { get; set; }

    public string SecurityField5 { get; set; }

    public string SecurityField6 { get; set; }

    public string ResponseSuccessUrl { get; set; }

    public string ResponseFailUrl { get; set; }

    public bool IsPaymentAwaitResponse { get; set; }

    public string IntegrationKey { get; set; }

    public DateTime CreatedDate { get; set; }

    public int CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public int? ModifiedBy { get; set; }

    public bool IsDeleted { get; set; }

    public int? MigrationId { get; set; }

    public virtual Country Country { get; set; }
}