// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CountryDashboard.Domain.Entities;

public partial class TexasContext : DbContext
{
    public TexasContext(DbContextOptions<TexasContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Aggregator> Aggregators { get; set; }

    public virtual DbSet<Area> Areas { get; set; }

    public virtual DbSet<AuthenticationPlatform> AuthenticationPlatforms { get; set; }

    public virtual DbSet<AuthenticationType> AuthenticationTypes { get; set; }

    public virtual DbSet<BannerSizeType> BannerSizeTypes { get; set; }

    public virtual DbSet<BannerType> BannerTypes { get; set; }

    public virtual DbSet<CateringConfig> CateringConfigs { get; set; }

    public virtual DbSet<Citizenship> Citizenships { get; set; }

    public virtual DbSet<CitizenshipLang> CitizenshipLangs { get; set; }

    public virtual DbSet<City> Cities { get; set; }

    public virtual DbSet<ContactMethod> ContactMethods { get; set; }

    public virtual DbSet<Country> Countries { get; set; }

    public virtual DbSet<DealType> DealTypes { get; set; }

    public virtual DbSet<DeleteReason> DeleteReasons { get; set; }

    public virtual DbSet<DisplayMode> DisplayModes { get; set; }

    public virtual DbSet<Extension> Extensions { get; set; }

    public virtual DbSet<Facility> Facilities { get; set; }

    public virtual DbSet<FacilityLang> FacilityLangs { get; set; }

    public virtual DbSet<Language> Languages { get; set; }

    public virtual DbSet<LoyaltyConfig> LoyaltyConfigs { get; set; }

    public virtual DbSet<Module> Modules { get; set; }

    public virtual DbSet<OrderStatus> OrderStatuses { get; set; }

    public virtual DbSet<OrderType> OrderTypes { get; set; }

    public virtual DbSet<OrderType> OrderTypes1 { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<PaymentOrderType> PaymentOrderTypes { get; set; }

    public virtual DbSet<PaymentRequestSource> PaymentRequestSources { get; set; }

    public virtual DbSet<PaymentType> PaymentTypes { get; set; }

    public virtual DbSet<PrivacyRequestType> PrivacyRequestTypes { get; set; }

    public virtual DbSet<Reference> References { get; set; }

    public virtual DbSet<RequestSource> RequestSources { get; set; }

    public virtual DbSet<SocialPlatform> SocialPlatforms { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Aggregator>(entity =>
        {
            entity.ToTable("Aggregator", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Description).HasMaxLength(1000);
            entity.Property(e => e.DescriptionNative).HasMaxLength(1000);
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Aggregator_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IconUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("IconURL");
            entity.Property(e => e.IntegrationKey).HasMaxLength(255);
            entity.Property(e => e.Link).HasMaxLength(255);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NameUnique)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Area>(entity =>
        {
            entity.ToTable("Area", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CityId).HasColumnName("CityID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Area_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.Integrationkey)
                .HasMaxLength(255)
                .HasDefaultValue("-1")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Area__Integratio__3572E547");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NameUnique).HasMaxLength(255);

            entity.HasOne(d => d.City).WithMany(p => p.Areas)
                .HasForeignKey(d => d.CityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Area_City");
        });

        modelBuilder.Entity<AuthenticationPlatform>(entity =>
        {
            entity.ToTable("AuthenticationPlatform", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AuthenticationTypeId).HasColumnName("AuthenticationTypeID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AuthenticationPlatform_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IntegrationKey).HasMaxLength(255);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Country).WithMany(p => p.AuthenticationPlatforms)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AuthenticationPlatform_Country");
        });

        modelBuilder.Entity<AuthenticationType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("enums_authenticationtype_id_primary");

            entity.ToTable("AuthenticationType", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_AuthenticationType_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NameUnique)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<BannerSizeType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__BannerSi__3214EC27DFD3D3AB");

            entity.ToTable("BannerSizeType", "Enum");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.Guid).HasColumnName("GUID");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<BannerType>(entity =>
        {
            entity.ToTable("BannerType", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_BannerType_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<CateringConfig>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Catering__3214EC0728240B69");

            entity.ToTable("CateringConfig", "Country");

            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DelevaryCharge).HasAnnotation("Relational:DefaultConstraintName", "DF_CountryCateringConfig_CateringDelevaryCharge");
            entity.Property(e => e.MaxOrderHours).HasAnnotation("Relational:DefaultConstraintName", "DF_CountryCateringConfig_CateringMaxOrderHours");
            entity.Property(e => e.MinOrderHours).HasAnnotation("Relational:DefaultConstraintName", "DF_CountryCateringConfig_CateringMinOrderHours");
            entity.Property(e => e.MinValue).HasAnnotation("Relational:DefaultConstraintName", "DF_CountryCateringConfig_CateringMinValue");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Country).WithMany(p => p.CateringConfigs)
                .HasForeignKey(d => d.CountryId)
                .HasConstraintName("FK_CountryCateringConfig_Country");
        });

        modelBuilder.Entity<Citizenship>(entity =>
        {
            entity.ToTable("Citizenship", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Citizenship_CreationDate")
                .HasColumnType("datetime");
            entity.Property(e => e.DisplayOrder).HasAnnotation("Relational:DefaultConstraintName", "DF_Citizenship_DisplayOrder");
            entity.Property(e => e.LastModificationDate).HasColumnType("datetime");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Citizenship_Status");
        });

        modelBuilder.Entity<CitizenshipLang>(entity =>
        {
            entity.HasKey(e => new { e.CitizenshipId, e.LangId });

            entity.ToTable("CitizenshipLang", "Country");

            entity.Property(e => e.CitizenshipId).HasColumnName("CitizenshipID");
            entity.Property(e => e.CreationDate)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CitizenshipLang_CreationDate")
                .HasColumnType("datetime");
            entity.Property(e => e.LastModificationDate).HasColumnType("datetime");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
        });

        modelBuilder.Entity<City>(entity =>
        {
            entity.ToTable("City", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_City_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IntegrationKey)
                .HasMaxLength(255)
                .HasDefaultValue("-1")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__City__Integratio__42CCE065");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NameUnique).HasMaxLength(255);

            entity.HasOne(d => d.Country).WithMany(p => p.Cities)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_City_Country");
        });

        modelBuilder.Entity<ContactMethod>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("enums_contactmethod_id_primary");

            entity.ToTable("ContactMethod", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_ContactMethod_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NameUnique)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Country>(entity =>
        {
            entity.ToTable("Country", "Country");

            entity.HasIndex(e => e.NameUnique, "UN_Country_NameUnique").IsUnique();

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("ID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.FlagUrl)
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnName("FlagURL");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Country_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IntegrationKey)
                .HasMaxLength(255)
                .HasDefaultValue("-1")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Country_IntegrationKey");
            entity.Property(e => e.IsTwoFactorEnabled)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Country_IsTwoFactorEnabled");
            entity.Property(e => e.Isocode)
                .IsRequired()
                .HasMaxLength(2)
                .HasDefaultValue("eg")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Country_CountryISOCode")
                .HasColumnName("ISOCode");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NameUnique).HasMaxLength(255);
            entity.Property(e => e.RegionName).HasMaxLength(255);
            entity.Property(e => e.RegionNameNative).HasMaxLength(255);
            entity.Property(e => e.WebsiteUrl)
                .HasMaxLength(255)
                .HasColumnName("WebsiteURL");
        });

        modelBuilder.Entity<DealType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("enum_dealtypes_id_primary");

            entity.ToTable("DealTypes", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_DealTypes_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_DealTypes_IsDeleted");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<DeleteReason>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("enum_deletereason_id_primary");

            entity.ToTable("DeleteReason", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_DeleteReason_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Reason)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<DisplayMode>(entity =>
        {
            entity.ToTable("DisplayMode", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_DisplayMode_IsDeleted");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Extension>(entity =>
        {
            entity.HasKey(e => e.CountryId);

            entity.ToTable("Extension", "Country");

            entity.Property(e => e.CountryId)
                .ValueGeneratedNever()
                .HasColumnName("CountryID");
            entity.Property(e => e.CmpId)
                .HasMaxLength(35)
                .HasColumnName("cmpID");
            entity.Property(e => e.CountryPhoneCode).HasMaxLength(10);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.CurrencyIsocode)
                .HasMaxLength(3)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "CountryExtension_CurrencyIsoCode")
                .HasColumnName("CurrencyISOCode");
            entity.Property(e => e.CurrencyName).HasMaxLength(30);
            entity.Property(e => e.CurrencyNameNative).HasMaxLength(30);
            entity.Property(e => e.CustomerServiceLine).HasMaxLength(200);
            entity.Property(e => e.EnableAddressMapLocation)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_EnableAddressMapLocation");
            entity.Property(e => e.EnableAgeConfirmation)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_EnableAgeConfirmation");
            entity.Property(e => e.EnableCalories).HasAnnotation("Relational:DefaultConstraintName", "CountryExtension_CaloriesEnabled_Default");
            entity.Property(e => e.EnableCmp).HasColumnName("EnableCMP");
            entity.Property(e => e.EnableMarketingConfirmation)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_EnableMarketingConfirmation");
            entity.Property(e => e.EnableOrderNotificationConfirmation)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_EnableOrderNotificationConfirmation");
            entity.Property(e => e.EnablePrivacyPolicyConfirmation)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_EnablePrivacyPolicyConfirmation");
            entity.Property(e => e.EnableTermsConfirmation)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_EnableTermsConfirmation");
            entity.Property(e => e.IsBogodiscountEnabled).HasColumnName("IsBOGODiscountEnabled");
            entity.Property(e => e.IsDeliveryTrackingPopupIosenabled).HasColumnName("IsDeliveryTrackingPopupIOSEnabled");
            entity.Property(e => e.IsTaxInclusive).HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_TaxInclusive");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.OrderEmail)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.PhoneRegex)
                .IsRequired()
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "CountryExtension_PhoneCode");
            entity.Property(e => e.TaxLabelDisplayName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TaxLabelDisplayNameNative)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TikTokAndroidAppId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TikTokIosAppId)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TimeDifference)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_TimeDifference");
            entity.Property(e => e.TotalDiscountPercentage)
                .HasDefaultValue(0.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_TotalDiscountPercentage");
            entity.Property(e => e.TotalDiscountValue)
                .HasDefaultValue(0.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryExtension_TotalDiscountValue");

            entity.HasOne(d => d.Country).WithOne(p => p.Extension)
                .HasForeignKey<Extension>(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountryExtension_Country");
        });

        modelBuilder.Entity<Facility>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_CountryFacility");

            entity.ToTable("Facility", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DisplayOrder)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Facility_DisplayOrder");
            entity.Property(e => e.Guid).HasColumnName("GUID");
            entity.Property(e => e.IconUrl)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("IconURL");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.NameUnique)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<FacilityLang>(entity =>
        {
            entity.HasKey(e => new { e.FacilityId, e.LanguageId }).HasName("PK_CountryFacilityLang");

            entity.ToTable("FacilityLang", "Country");

            entity.Property(e => e.FacilityId).HasColumnName("FacilityID");
            entity.Property(e => e.LanguageId).HasColumnName("LanguageID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<Language>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_CountryLanguage");

            entity.ToTable("Language", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(5);
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Direction)
                .IsRequired()
                .HasMaxLength(3);
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Language_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IntegrationKey).HasMaxLength(255);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Country).WithMany(p => p.Languages)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountryLanguage_Country");
        });

        modelBuilder.Entity<LoyaltyConfig>(entity =>
        {
            entity.HasKey(e => e.CountryId).HasName("PK_LoyaltyConfig_1");

            entity.ToTable("LoyaltyConfig", "Country");

            entity.Property(e => e.CountryId)
                .ValueGeneratedNever()
                .HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.PointsExpire).HasAnnotation("Relational:DefaultConstraintName", "DF_CountryLoyaltyConfig_PointsExpire");

            entity.HasOne(d => d.Country).WithOne(p => p.LoyaltyConfig)
                .HasForeignKey<LoyaltyConfig>(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountryLoyaltyConfig_Country");
        });

        modelBuilder.Entity<Module>(entity =>
        {
            entity.ToTable("Module", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<OrderStatus>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("country_orderstatus_id_primary");

            entity.ToTable("OrderStatus", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OrderStatus_GUID_1")
                .HasColumnName("GUID");
            entity.Property(e => e.IntegrationKey).HasMaxLength(255);
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_OrderStatus_IsDeleted");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.NameUnique)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.StatusIconOff)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.StatusIconOn)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Country).WithMany(p => p.OrderStatuses)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderStatus_Country");
        });

        modelBuilder.Entity<OrderType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_OrderTypes");

            entity.ToTable("OrderType", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OrderType_CountryID")
                .HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OrderType_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IconUrl)
                .IsRequired()
                .HasMaxLength(400)
                .HasColumnName("IconURL");
            entity.Property(e => e.IntegrationKey)
                .HasMaxLength(255)
                .HasDefaultValue("-1")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OrderTypes_Integrationkey");
            entity.Property(e => e.IsBogodiscountEnabled).HasColumnName("IsBOGODiscountEnabled");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(400);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(400);
            entity.Property(e => e.NameUnique).HasMaxLength(255);
            entity.Property(e => e.TotalDiscountPercentage)
                .HasDefaultValue(0.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OrderType_TotalDiscountPercentage");
            entity.Property(e => e.TotalDiscountValue)
                .HasDefaultValue(0.0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_OrderType_TotalDiscountValue");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");

            entity.HasOne(d => d.Country).WithMany(p => p.OrderTypes)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderType_Country");

            entity.HasOne(d => d.Type).WithMany(p => p.OrderTypes)
                .HasForeignKey(d => d.TypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderType_OrderType");
        });

        modelBuilder.Entity<OrderType>(entity =>
        {
            entity.ToTable("OrderType", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(400);
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_CountryPayment");

            entity.ToTable("Payment", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Payment_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IntegrationKey)
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_CountryPayment_IntegrationKey");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Payment_IsDeleted");
            entity.Property(e => e.LogoUrl)
                .IsRequired()
                .HasMaxLength(2000)
                .HasColumnName("LogoURL");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NameNative)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.NameUnique).HasMaxLength(200);
            entity.Property(e => e.ResponseFailUrl)
                .HasMaxLength(400)
                .HasColumnName("ResponseFailURL");
            entity.Property(e => e.ResponseSuccessUrl)
                .HasMaxLength(400)
                .HasColumnName("ResponseSuccessURL");
            entity.Property(e => e.SecurityField1)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.SecurityField2)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.SecurityField3)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.SecurityField4)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.SecurityField5)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.SecurityField6)
                .IsRequired()
                .HasMaxLength(4000);
            entity.Property(e => e.StoreId).HasColumnName("StoreID");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(4000)
                .HasColumnName("URL");

            entity.HasOne(d => d.Country).WithMany(p => p.Payments)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountryPayment_Country");
        });

        modelBuilder.Entity<PaymentOrderType>(entity =>
        {
            entity.HasKey(e => new { e.OrderTypeId, e.PaymentId });

            entity.ToTable("PaymentOrderType", "Country");

            entity.Property(e => e.OrderTypeId).HasColumnName("OrderTypeID");
            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.IntegrationKey)
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PaymentOrderType_IntegrationKey");
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_Country.PaymentOrderType_IsDeleted");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");

            entity.HasOne(d => d.OrderType).WithMany(p => p.PaymentOrderTypes)
                .HasForeignKey(d => d.OrderTypeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PaymentOrderType_OrderType");
        });

        modelBuilder.Entity<PaymentRequestSource>(entity =>
        {
            entity.HasKey(e => new { e.PaymentId, e.RequestSource });

            entity.ToTable("PaymentRequestSource", "Country");

            entity.Property(e => e.PaymentId).HasColumnName("PaymentID");
            entity.Property(e => e.RequestSource).HasMaxLength(200);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DeviceModel).HasMaxLength(200);
            entity.Property(e => e.IsDeleted).HasAnnotation("Relational:DefaultConstraintName", "DF_PaymentRequestSource_IsDeleted");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
        });

        modelBuilder.Entity<PaymentType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentT__3214EC27427EB535");

            entity.ToTable("PaymentType", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Guid).HasColumnName("GUID");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<PrivacyRequestType>(entity =>
        {
            entity.ToTable("PrivacyRequestType", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_PrivacyRequestType_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<Reference>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("enum_reference_id_primary");

            entity.ToTable("Reference", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.AffectOnPoints).HasMaxLength(50);
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Reference_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IsDeleted)
                .IsRequired()
                .HasDefaultValueSql("('0')")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Reference__IsDel__468862B0");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<RequestSource>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("enums_requestSource_id_primary");

            entity.ToTable("RequestSource", "Enum");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RequestSource_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);
        });

        modelBuilder.Entity<SocialPlatform>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_CountrySocialPlatform");

            entity.ToTable("SocialPlatform", "Country");

            entity.Property(e => e.Id).HasColumnName("ID");
            entity.Property(e => e.CountryId).HasColumnName("CountryID");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Guid)
                .HasDefaultValueSql("(newid())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SocialPlatform_GUID")
                .HasColumnName("GUID");
            entity.Property(e => e.IconUrl)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("IconURL");
            entity.Property(e => e.IntegrationKey)
                .HasMaxLength(255)
                .HasDefaultValue("")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SocialPlatform_IntegrationKey");
            entity.Property(e => e.IsDeleted)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_SocialPlatform_IsDeleted");
            entity.Property(e => e.MigrationId).HasColumnName("MigrationID");
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("URL");

            entity.HasOne(d => d.Country).WithMany(p => p.SocialPlatforms)
                .HasForeignKey(d => d.CountryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CountrySocialPlatform_Country");
        });
        modelBuilder.HasSequence("InstanceID_Sequence").StartsAt(18L);

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}